/*** Autogenerated by WIDL 9.16 from tests/dxcompiler.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __dxcompiler_h__
#define __dxcompiler_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __IUnknown_FWD_DEFINED__
#define __IUnknown_FWD_DEFINED__
typedef interface IUnknown IUnknown;
#ifdef __cplusplus
interface IUnknown;
#endif /* __cplusplus */
#endif

#ifndef __DxcCompiler_FWD_DEFINED__
#define __DxcCompiler_FWD_DEFINED__
#ifdef __cplusplus
typedef class DxcCompiler DxcCompiler;
#else
typedef struct DxcCompiler DxcCompiler;
#endif /* defined __cplusplus */
#endif /* defined __DxcCompiler_FWD_DEFINED__ */

#ifndef __IDxcBlob_FWD_DEFINED__
#define __IDxcBlob_FWD_DEFINED__
typedef interface IDxcBlob IDxcBlob;
#ifdef __cplusplus
interface IDxcBlob;
#endif /* __cplusplus */
#endif

#ifndef __IDxcBlobEncoding_FWD_DEFINED__
#define __IDxcBlobEncoding_FWD_DEFINED__
typedef interface IDxcBlobEncoding IDxcBlobEncoding;
#ifdef __cplusplus
interface IDxcBlobEncoding;
#endif /* __cplusplus */
#endif

#ifndef __IDxcBlobUtf8_FWD_DEFINED__
#define __IDxcBlobUtf8_FWD_DEFINED__
typedef interface IDxcBlobUtf8 IDxcBlobUtf8;
#ifdef __cplusplus
interface IDxcBlobUtf8;
#endif /* __cplusplus */
#endif

#ifndef __IDxcBlobUtf16_FWD_DEFINED__
#define __IDxcBlobUtf16_FWD_DEFINED__
typedef interface IDxcBlobUtf16 IDxcBlobUtf16;
#ifdef __cplusplus
interface IDxcBlobUtf16;
#endif /* __cplusplus */
#endif

#ifndef __IDxcIncludeHandler_FWD_DEFINED__
#define __IDxcIncludeHandler_FWD_DEFINED__
typedef interface IDxcIncludeHandler IDxcIncludeHandler;
#ifdef __cplusplus
interface IDxcIncludeHandler;
#endif /* __cplusplus */
#endif

#ifndef __IDxcOperationResult_FWD_DEFINED__
#define __IDxcOperationResult_FWD_DEFINED__
typedef interface IDxcOperationResult IDxcOperationResult;
#ifdef __cplusplus
interface IDxcOperationResult;
#endif /* __cplusplus */
#endif

#ifndef __IDxcResult_FWD_DEFINED__
#define __IDxcResult_FWD_DEFINED__
typedef interface IDxcResult IDxcResult;
#ifdef __cplusplus
interface IDxcResult;
#endif /* __cplusplus */
#endif

#ifndef __IDxcCompiler3_FWD_DEFINED__
#define __IDxcCompiler3_FWD_DEFINED__
typedef interface IDxcCompiler3 IDxcCompiler3;
#ifdef __cplusplus
interface IDxcCompiler3;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <vkd3d_windows.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __VKD3D_UNKNOWN_H
#define __VKD3D_UNKNOWN_H
#if 0
typedef IID *REFIID;
typedef IID *REFGUID;
typedef GUID CLSID;
typedef GUID *LPCLSID;
typedef CLSID *REFCLSID;
#endif
#if !defined(_WIN32)
typedef void *HWND;
typedef void *HMODULE;
typedef struct LUID {
    DWORD LowPart;
    LONG HighPart;
} LUID;
typedef struct _RECT {
    LONG left;
    LONG top;
    LONG right;
    LONG bottom;
} RECT;
#endif
/*****************************************************************************
 * IUnknown interface
 */
#ifndef __IUnknown_INTERFACE_DEFINED__
#define __IUnknown_INTERFACE_DEFINED__

DEFINE_GUID(IID_IUnknown, 0x00000000, 0x0000, 0x0000, 0xc0,0x00, 0x00,0x00,0x00,0x00,0x00,0x46);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("00000000-0000-0000-c000-000000000046")
IUnknown
{

    BEGIN_INTERFACE

    virtual HRESULT STDMETHODCALLTYPE QueryInterface(
        REFIID riid,
        void **object) = 0;

    virtual ULONG STDMETHODCALLTYPE AddRef(
        ) = 0;

    virtual ULONG STDMETHODCALLTYPE Release(
        ) = 0;

    END_INTERFACE

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IUnknown, 0x00000000, 0x0000, 0x0000, 0xc0,0x00, 0x00,0x00,0x00,0x00,0x00,0x46)
#endif
#else
typedef struct IUnknownVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IUnknown *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IUnknown *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IUnknown *This);

    END_INTERFACE
} IUnknownVtbl;

interface IUnknown {
    CONST_VTBL IUnknownVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IUnknown_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IUnknown_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IUnknown_Release(This) (This)->lpVtbl->Release(This)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IUnknown_QueryInterface(IUnknown* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IUnknown_AddRef(IUnknown* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IUnknown_Release(IUnknown* This) {
    return This->lpVtbl->Release(This);
}
#endif
#endif

#endif


#endif  /* __IUnknown_INTERFACE_DEFINED__ */

#endif   /* __VKD3D_UNKNOWN_H */
#if defined(__x86_64__) && !defined(_WIN32)
# pragma push_macro("__stdcall")
# undef __stdcall
# define __stdcall
#endif
#define DXC_E_LLVM_CAST_ERROR (0x80aa001d)

/*****************************************************************************
 * DxcCompiler coclass
 */

DEFINE_GUID(CLSID_DxcCompiler, 0x73e22d93, 0xe6ce, 0x47f3, 0xb5,0xbf, 0xf0,0x66,0x4f,0x39,0xc1,0xb0);

#ifdef __cplusplus
class DECLSPEC_UUID("73e22d93-e6ce-47f3-b5bf-f0664f39c1b0") DxcCompiler;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(DxcCompiler, 0x73e22d93, 0xe6ce, 0x47f3, 0xb5,0xbf, 0xf0,0x66,0x4f,0x39,0xc1,0xb0)
#endif
#endif

/*****************************************************************************
 * IDxcBlob interface
 */
#ifndef __IDxcBlob_INTERFACE_DEFINED__
#define __IDxcBlob_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcBlob, 0x8ba5fb08, 0x5195, 0x40e2, 0xac,0x58, 0x0d,0x98,0x9c,0x3a,0x01,0x02);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("8ba5fb08-5195-40e2-ac58-0d989c3a0102")
IDxcBlob : public IUnknown
{
    virtual void * STDMETHODCALLTYPE GetBufferPointer(
        ) = 0;

    virtual SIZE_T STDMETHODCALLTYPE GetBufferSize(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcBlob, 0x8ba5fb08, 0x5195, 0x40e2, 0xac,0x58, 0x0d,0x98,0x9c,0x3a,0x01,0x02)
#endif
#else
typedef struct IDxcBlobVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcBlob *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcBlob *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcBlob *This);

    /*** IDxcBlob methods ***/
    void * (STDMETHODCALLTYPE *GetBufferPointer)(
        IDxcBlob *This);

    SIZE_T (STDMETHODCALLTYPE *GetBufferSize)(
        IDxcBlob *This);

    END_INTERFACE
} IDxcBlobVtbl;

interface IDxcBlob {
    CONST_VTBL IDxcBlobVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcBlob_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcBlob_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcBlob_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcBlob methods ***/
#define IDxcBlob_GetBufferPointer(This) (This)->lpVtbl->GetBufferPointer(This)
#define IDxcBlob_GetBufferSize(This) (This)->lpVtbl->GetBufferSize(This)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcBlob_QueryInterface(IDxcBlob* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcBlob_AddRef(IDxcBlob* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcBlob_Release(IDxcBlob* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcBlob methods ***/
static __WIDL_INLINE void * IDxcBlob_GetBufferPointer(IDxcBlob* This) {
    return This->lpVtbl->GetBufferPointer(This);
}
static __WIDL_INLINE SIZE_T IDxcBlob_GetBufferSize(IDxcBlob* This) {
    return This->lpVtbl->GetBufferSize(This);
}
#endif
#endif

#endif


#endif  /* __IDxcBlob_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IDxcBlobEncoding interface
 */
#ifndef __IDxcBlobEncoding_INTERFACE_DEFINED__
#define __IDxcBlobEncoding_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcBlobEncoding, 0x7241d424, 0x2646, 0x4191, 0x97,0xc0, 0x98,0xe9,0x6e,0x42,0xfc,0x68);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("7241d424-2646-4191-97c0-98e96e42fc68")
IDxcBlobEncoding : public IDxcBlob
{
    virtual HRESULT STDMETHODCALLTYPE GetEncoding(
        BOOL *known,
        UINT32 *code_page) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcBlobEncoding, 0x7241d424, 0x2646, 0x4191, 0x97,0xc0, 0x98,0xe9,0x6e,0x42,0xfc,0x68)
#endif
#else
typedef struct IDxcBlobEncodingVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcBlobEncoding *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcBlobEncoding *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcBlobEncoding *This);

    /*** IDxcBlob methods ***/
    void * (STDMETHODCALLTYPE *GetBufferPointer)(
        IDxcBlobEncoding *This);

    SIZE_T (STDMETHODCALLTYPE *GetBufferSize)(
        IDxcBlobEncoding *This);

    /*** IDxcBlobEncoding methods ***/
    HRESULT (STDMETHODCALLTYPE *GetEncoding)(
        IDxcBlobEncoding *This,
        BOOL *known,
        UINT32 *code_page);

    END_INTERFACE
} IDxcBlobEncodingVtbl;

interface IDxcBlobEncoding {
    CONST_VTBL IDxcBlobEncodingVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcBlobEncoding_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcBlobEncoding_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcBlobEncoding_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcBlob methods ***/
#define IDxcBlobEncoding_GetBufferPointer(This) (This)->lpVtbl->GetBufferPointer(This)
#define IDxcBlobEncoding_GetBufferSize(This) (This)->lpVtbl->GetBufferSize(This)
/*** IDxcBlobEncoding methods ***/
#define IDxcBlobEncoding_GetEncoding(This,known,code_page) (This)->lpVtbl->GetEncoding(This,known,code_page)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcBlobEncoding_QueryInterface(IDxcBlobEncoding* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcBlobEncoding_AddRef(IDxcBlobEncoding* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcBlobEncoding_Release(IDxcBlobEncoding* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcBlob methods ***/
static __WIDL_INLINE void * IDxcBlobEncoding_GetBufferPointer(IDxcBlobEncoding* This) {
    return This->lpVtbl->GetBufferPointer(This);
}
static __WIDL_INLINE SIZE_T IDxcBlobEncoding_GetBufferSize(IDxcBlobEncoding* This) {
    return This->lpVtbl->GetBufferSize(This);
}
/*** IDxcBlobEncoding methods ***/
static __WIDL_INLINE HRESULT IDxcBlobEncoding_GetEncoding(IDxcBlobEncoding* This,BOOL *known,UINT32 *code_page) {
    return This->lpVtbl->GetEncoding(This,known,code_page);
}
#endif
#endif

#endif


#endif  /* __IDxcBlobEncoding_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IDxcBlobUtf8 interface
 */
#ifndef __IDxcBlobUtf8_INTERFACE_DEFINED__
#define __IDxcBlobUtf8_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcBlobUtf8, 0x3da636c9, 0xba71, 0x4024, 0xa3,0x01, 0x30,0xcb,0xf1,0x25,0x30,0x5b);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("3da636c9-ba71-4024-a301-30cbf125305b")
IDxcBlobUtf8 : public IDxcBlobEncoding
{
    virtual const char * STDMETHODCALLTYPE GetStringPointer(
        ) = 0;

    virtual SIZE_T STDMETHODCALLTYPE GetStringLength(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcBlobUtf8, 0x3da636c9, 0xba71, 0x4024, 0xa3,0x01, 0x30,0xcb,0xf1,0x25,0x30,0x5b)
#endif
#else
typedef struct IDxcBlobUtf8Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcBlobUtf8 *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcBlobUtf8 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcBlobUtf8 *This);

    /*** IDxcBlob methods ***/
    void * (STDMETHODCALLTYPE *GetBufferPointer)(
        IDxcBlobUtf8 *This);

    SIZE_T (STDMETHODCALLTYPE *GetBufferSize)(
        IDxcBlobUtf8 *This);

    /*** IDxcBlobEncoding methods ***/
    HRESULT (STDMETHODCALLTYPE *GetEncoding)(
        IDxcBlobUtf8 *This,
        BOOL *known,
        UINT32 *code_page);

    /*** IDxcBlobUtf8 methods ***/
    const char * (STDMETHODCALLTYPE *GetStringPointer)(
        IDxcBlobUtf8 *This);

    SIZE_T (STDMETHODCALLTYPE *GetStringLength)(
        IDxcBlobUtf8 *This);

    END_INTERFACE
} IDxcBlobUtf8Vtbl;

interface IDxcBlobUtf8 {
    CONST_VTBL IDxcBlobUtf8Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcBlobUtf8_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcBlobUtf8_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcBlobUtf8_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcBlob methods ***/
#define IDxcBlobUtf8_GetBufferPointer(This) (This)->lpVtbl->GetBufferPointer(This)
#define IDxcBlobUtf8_GetBufferSize(This) (This)->lpVtbl->GetBufferSize(This)
/*** IDxcBlobEncoding methods ***/
#define IDxcBlobUtf8_GetEncoding(This,known,code_page) (This)->lpVtbl->GetEncoding(This,known,code_page)
/*** IDxcBlobUtf8 methods ***/
#define IDxcBlobUtf8_GetStringPointer(This) (This)->lpVtbl->GetStringPointer(This)
#define IDxcBlobUtf8_GetStringLength(This) (This)->lpVtbl->GetStringLength(This)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcBlobUtf8_QueryInterface(IDxcBlobUtf8* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcBlobUtf8_AddRef(IDxcBlobUtf8* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcBlobUtf8_Release(IDxcBlobUtf8* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcBlob methods ***/
static __WIDL_INLINE void * IDxcBlobUtf8_GetBufferPointer(IDxcBlobUtf8* This) {
    return This->lpVtbl->GetBufferPointer(This);
}
static __WIDL_INLINE SIZE_T IDxcBlobUtf8_GetBufferSize(IDxcBlobUtf8* This) {
    return This->lpVtbl->GetBufferSize(This);
}
/*** IDxcBlobEncoding methods ***/
static __WIDL_INLINE HRESULT IDxcBlobUtf8_GetEncoding(IDxcBlobUtf8* This,BOOL *known,UINT32 *code_page) {
    return This->lpVtbl->GetEncoding(This,known,code_page);
}
/*** IDxcBlobUtf8 methods ***/
static __WIDL_INLINE const char * IDxcBlobUtf8_GetStringPointer(IDxcBlobUtf8* This) {
    return This->lpVtbl->GetStringPointer(This);
}
static __WIDL_INLINE SIZE_T IDxcBlobUtf8_GetStringLength(IDxcBlobUtf8* This) {
    return This->lpVtbl->GetStringLength(This);
}
#endif
#endif

#endif


#endif  /* __IDxcBlobUtf8_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IDxcBlobUtf16 interface
 */
#ifndef __IDxcBlobUtf16_INTERFACE_DEFINED__
#define __IDxcBlobUtf16_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcBlobUtf16, 0xa3f84eab, 0x0faa, 0x497e, 0xa3,0x9c, 0xee,0x6e,0xd6,0x0b,0x2d,0x84);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("a3f84eab-0faa-497e-a39c-ee6ed60b2d84")
IDxcBlobUtf16 : public IDxcBlobEncoding
{
    virtual const WCHAR * STDMETHODCALLTYPE GetStringPointer(
        ) = 0;

    virtual SIZE_T STDMETHODCALLTYPE GetStringLength(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcBlobUtf16, 0xa3f84eab, 0x0faa, 0x497e, 0xa3,0x9c, 0xee,0x6e,0xd6,0x0b,0x2d,0x84)
#endif
#else
typedef struct IDxcBlobUtf16Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcBlobUtf16 *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcBlobUtf16 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcBlobUtf16 *This);

    /*** IDxcBlob methods ***/
    void * (STDMETHODCALLTYPE *GetBufferPointer)(
        IDxcBlobUtf16 *This);

    SIZE_T (STDMETHODCALLTYPE *GetBufferSize)(
        IDxcBlobUtf16 *This);

    /*** IDxcBlobEncoding methods ***/
    HRESULT (STDMETHODCALLTYPE *GetEncoding)(
        IDxcBlobUtf16 *This,
        BOOL *known,
        UINT32 *code_page);

    /*** IDxcBlobUtf16 methods ***/
    const WCHAR * (STDMETHODCALLTYPE *GetStringPointer)(
        IDxcBlobUtf16 *This);

    SIZE_T (STDMETHODCALLTYPE *GetStringLength)(
        IDxcBlobUtf16 *This);

    END_INTERFACE
} IDxcBlobUtf16Vtbl;

interface IDxcBlobUtf16 {
    CONST_VTBL IDxcBlobUtf16Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcBlobUtf16_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcBlobUtf16_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcBlobUtf16_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcBlob methods ***/
#define IDxcBlobUtf16_GetBufferPointer(This) (This)->lpVtbl->GetBufferPointer(This)
#define IDxcBlobUtf16_GetBufferSize(This) (This)->lpVtbl->GetBufferSize(This)
/*** IDxcBlobEncoding methods ***/
#define IDxcBlobUtf16_GetEncoding(This,known,code_page) (This)->lpVtbl->GetEncoding(This,known,code_page)
/*** IDxcBlobUtf16 methods ***/
#define IDxcBlobUtf16_GetStringPointer(This) (This)->lpVtbl->GetStringPointer(This)
#define IDxcBlobUtf16_GetStringLength(This) (This)->lpVtbl->GetStringLength(This)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcBlobUtf16_QueryInterface(IDxcBlobUtf16* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcBlobUtf16_AddRef(IDxcBlobUtf16* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcBlobUtf16_Release(IDxcBlobUtf16* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcBlob methods ***/
static __WIDL_INLINE void * IDxcBlobUtf16_GetBufferPointer(IDxcBlobUtf16* This) {
    return This->lpVtbl->GetBufferPointer(This);
}
static __WIDL_INLINE SIZE_T IDxcBlobUtf16_GetBufferSize(IDxcBlobUtf16* This) {
    return This->lpVtbl->GetBufferSize(This);
}
/*** IDxcBlobEncoding methods ***/
static __WIDL_INLINE HRESULT IDxcBlobUtf16_GetEncoding(IDxcBlobUtf16* This,BOOL *known,UINT32 *code_page) {
    return This->lpVtbl->GetEncoding(This,known,code_page);
}
/*** IDxcBlobUtf16 methods ***/
static __WIDL_INLINE const WCHAR * IDxcBlobUtf16_GetStringPointer(IDxcBlobUtf16* This) {
    return This->lpVtbl->GetStringPointer(This);
}
static __WIDL_INLINE SIZE_T IDxcBlobUtf16_GetStringLength(IDxcBlobUtf16* This) {
    return This->lpVtbl->GetStringLength(This);
}
#endif
#endif

#endif


#endif  /* __IDxcBlobUtf16_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IDxcIncludeHandler interface
 */
#ifndef __IDxcIncludeHandler_INTERFACE_DEFINED__
#define __IDxcIncludeHandler_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcIncludeHandler, 0x7f61fc7d, 0x950d, 0x467f, 0xb3,0xe3, 0x3c,0x02,0xfb,0x49,0x18,0x7c);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("7f61fc7d-950d-467f-b3e3-3c02fb49187c")
IDxcIncludeHandler : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE LoadSource(
        const WCHAR *filename,
        IDxcBlob **include_source) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcIncludeHandler, 0x7f61fc7d, 0x950d, 0x467f, 0xb3,0xe3, 0x3c,0x02,0xfb,0x49,0x18,0x7c)
#endif
#else
typedef struct IDxcIncludeHandlerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcIncludeHandler *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcIncludeHandler *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcIncludeHandler *This);

    /*** IDxcIncludeHandler methods ***/
    HRESULT (STDMETHODCALLTYPE *LoadSource)(
        IDxcIncludeHandler *This,
        const WCHAR *filename,
        IDxcBlob **include_source);

    END_INTERFACE
} IDxcIncludeHandlerVtbl;

interface IDxcIncludeHandler {
    CONST_VTBL IDxcIncludeHandlerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcIncludeHandler_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcIncludeHandler_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcIncludeHandler_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcIncludeHandler methods ***/
#define IDxcIncludeHandler_LoadSource(This,filename,include_source) (This)->lpVtbl->LoadSource(This,filename,include_source)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcIncludeHandler_QueryInterface(IDxcIncludeHandler* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcIncludeHandler_AddRef(IDxcIncludeHandler* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcIncludeHandler_Release(IDxcIncludeHandler* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcIncludeHandler methods ***/
static __WIDL_INLINE HRESULT IDxcIncludeHandler_LoadSource(IDxcIncludeHandler* This,const WCHAR *filename,IDxcBlob **include_source) {
    return This->lpVtbl->LoadSource(This,filename,include_source);
}
#endif
#endif

#endif


#endif  /* __IDxcIncludeHandler_INTERFACE_DEFINED__ */

typedef struct DxcBuffer {
    const void *Ptr;
    SIZE_T Size;
    UINT Encoding;
} DxcBuffer;
/*****************************************************************************
 * IDxcOperationResult interface
 */
#ifndef __IDxcOperationResult_INTERFACE_DEFINED__
#define __IDxcOperationResult_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcOperationResult, 0xcedb484a, 0xd4e9, 0x445a, 0xb9,0x91, 0xca,0x21,0xca,0x15,0x7d,0xc2);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("cedb484a-d4e9-445a-b991-ca21ca157dc2")
IDxcOperationResult : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetStatus(
        HRESULT *status) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetResult(
        IDxcBlob **result) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetErrorBuffer(
        IDxcBlobEncoding **errors) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcOperationResult, 0xcedb484a, 0xd4e9, 0x445a, 0xb9,0x91, 0xca,0x21,0xca,0x15,0x7d,0xc2)
#endif
#else
typedef struct IDxcOperationResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcOperationResult *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcOperationResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcOperationResult *This);

    /*** IDxcOperationResult methods ***/
    HRESULT (STDMETHODCALLTYPE *GetStatus)(
        IDxcOperationResult *This,
        HRESULT *status);

    HRESULT (STDMETHODCALLTYPE *GetResult)(
        IDxcOperationResult *This,
        IDxcBlob **result);

    HRESULT (STDMETHODCALLTYPE *GetErrorBuffer)(
        IDxcOperationResult *This,
        IDxcBlobEncoding **errors);

    END_INTERFACE
} IDxcOperationResultVtbl;

interface IDxcOperationResult {
    CONST_VTBL IDxcOperationResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcOperationResult_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcOperationResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcOperationResult_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcOperationResult methods ***/
#define IDxcOperationResult_GetStatus(This,status) (This)->lpVtbl->GetStatus(This,status)
#define IDxcOperationResult_GetResult(This,result) (This)->lpVtbl->GetResult(This,result)
#define IDxcOperationResult_GetErrorBuffer(This,errors) (This)->lpVtbl->GetErrorBuffer(This,errors)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcOperationResult_QueryInterface(IDxcOperationResult* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcOperationResult_AddRef(IDxcOperationResult* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcOperationResult_Release(IDxcOperationResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcOperationResult methods ***/
static __WIDL_INLINE HRESULT IDxcOperationResult_GetStatus(IDxcOperationResult* This,HRESULT *status) {
    return This->lpVtbl->GetStatus(This,status);
}
static __WIDL_INLINE HRESULT IDxcOperationResult_GetResult(IDxcOperationResult* This,IDxcBlob **result) {
    return This->lpVtbl->GetResult(This,result);
}
static __WIDL_INLINE HRESULT IDxcOperationResult_GetErrorBuffer(IDxcOperationResult* This,IDxcBlobEncoding **errors) {
    return This->lpVtbl->GetErrorBuffer(This,errors);
}
#endif
#endif

#endif


#endif  /* __IDxcOperationResult_INTERFACE_DEFINED__ */

typedef enum DXC_OUT_KIND {
    DXC_OUT_NONE = 0,
    DXC_OUT_OBJECT = 1,
    DXC_OUT_ERRORS = 2,
    DXC_OUT_PDB = 3,
    DXC_OUT_SHADER_HASH = 4,
    DXC_OUT_DISASSEMBLY = 5,
    DXC_OUT_HLSL = 6,
    DXC_OUT_TEXT = 7,
    DXC_OUT_REFLECTION = 8,
    DXC_OUT_ROOT_SIGNATURE = 9,
    DXC_OUT_EXTRA_OUTPUTS = 10,
    DXC_OUT_FORCE_DWORD = 0xffffffff
} DXC_OUT_KIND;
/*****************************************************************************
 * IDxcResult interface
 */
#ifndef __IDxcResult_INTERFACE_DEFINED__
#define __IDxcResult_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcResult, 0x58346cda, 0xdde7, 0x4497, 0x94,0x61, 0x6f,0x87,0xaf,0x5e,0x06,0x59);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("58346cda-dde7-4497-9461-6f87af5e0659")
IDxcResult : public IDxcOperationResult
{
    virtual BOOL STDMETHODCALLTYPE HasOutput(
        DXC_OUT_KIND dxc_out_kind) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetOutput(
        DXC_OUT_KIND dxc_out_kind,
        REFIID iid,
        void **object,
        IDxcBlobUtf16 **output_name) = 0;

    virtual UINT32 STDMETHODCALLTYPE GetNumOutputs(
        ) = 0;

    virtual DXC_OUT_KIND STDMETHODCALLTYPE GetOutputByIndex(
        UINT32 index) = 0;

    virtual DXC_OUT_KIND STDMETHODCALLTYPE PrimaryOutput(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcResult, 0x58346cda, 0xdde7, 0x4497, 0x94,0x61, 0x6f,0x87,0xaf,0x5e,0x06,0x59)
#endif
#else
typedef struct IDxcResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcResult *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcResult *This);

    /*** IDxcOperationResult methods ***/
    HRESULT (STDMETHODCALLTYPE *GetStatus)(
        IDxcResult *This,
        HRESULT *status);

    HRESULT (STDMETHODCALLTYPE *GetResult)(
        IDxcResult *This,
        IDxcBlob **result);

    HRESULT (STDMETHODCALLTYPE *GetErrorBuffer)(
        IDxcResult *This,
        IDxcBlobEncoding **errors);

    /*** IDxcResult methods ***/
    BOOL (STDMETHODCALLTYPE *HasOutput)(
        IDxcResult *This,
        DXC_OUT_KIND dxc_out_kind);

    HRESULT (STDMETHODCALLTYPE *GetOutput)(
        IDxcResult *This,
        DXC_OUT_KIND dxc_out_kind,
        REFIID iid,
        void **object,
        IDxcBlobUtf16 **output_name);

    UINT32 (STDMETHODCALLTYPE *GetNumOutputs)(
        IDxcResult *This);

    DXC_OUT_KIND (STDMETHODCALLTYPE *GetOutputByIndex)(
        IDxcResult *This,
        UINT32 index);

    DXC_OUT_KIND (STDMETHODCALLTYPE *PrimaryOutput)(
        IDxcResult *This);

    END_INTERFACE
} IDxcResultVtbl;

interface IDxcResult {
    CONST_VTBL IDxcResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcResult_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcResult_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcOperationResult methods ***/
#define IDxcResult_GetStatus(This,status) (This)->lpVtbl->GetStatus(This,status)
#define IDxcResult_GetResult(This,result) (This)->lpVtbl->GetResult(This,result)
#define IDxcResult_GetErrorBuffer(This,errors) (This)->lpVtbl->GetErrorBuffer(This,errors)
/*** IDxcResult methods ***/
#define IDxcResult_HasOutput(This,dxc_out_kind) (This)->lpVtbl->HasOutput(This,dxc_out_kind)
#define IDxcResult_GetOutput(This,dxc_out_kind,iid,object,output_name) (This)->lpVtbl->GetOutput(This,dxc_out_kind,iid,object,output_name)
#define IDxcResult_GetNumOutputs(This) (This)->lpVtbl->GetNumOutputs(This)
#define IDxcResult_GetOutputByIndex(This,index) (This)->lpVtbl->GetOutputByIndex(This,index)
#define IDxcResult_PrimaryOutput(This) (This)->lpVtbl->PrimaryOutput(This)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcResult_QueryInterface(IDxcResult* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcResult_AddRef(IDxcResult* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcResult_Release(IDxcResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcOperationResult methods ***/
static __WIDL_INLINE HRESULT IDxcResult_GetStatus(IDxcResult* This,HRESULT *status) {
    return This->lpVtbl->GetStatus(This,status);
}
static __WIDL_INLINE HRESULT IDxcResult_GetResult(IDxcResult* This,IDxcBlob **result) {
    return This->lpVtbl->GetResult(This,result);
}
static __WIDL_INLINE HRESULT IDxcResult_GetErrorBuffer(IDxcResult* This,IDxcBlobEncoding **errors) {
    return This->lpVtbl->GetErrorBuffer(This,errors);
}
/*** IDxcResult methods ***/
static __WIDL_INLINE BOOL IDxcResult_HasOutput(IDxcResult* This,DXC_OUT_KIND dxc_out_kind) {
    return This->lpVtbl->HasOutput(This,dxc_out_kind);
}
static __WIDL_INLINE HRESULT IDxcResult_GetOutput(IDxcResult* This,DXC_OUT_KIND dxc_out_kind,REFIID iid,void **object,IDxcBlobUtf16 **output_name) {
    return This->lpVtbl->GetOutput(This,dxc_out_kind,iid,object,output_name);
}
static __WIDL_INLINE UINT32 IDxcResult_GetNumOutputs(IDxcResult* This) {
    return This->lpVtbl->GetNumOutputs(This);
}
static __WIDL_INLINE DXC_OUT_KIND IDxcResult_GetOutputByIndex(IDxcResult* This,UINT32 index) {
    return This->lpVtbl->GetOutputByIndex(This,index);
}
static __WIDL_INLINE DXC_OUT_KIND IDxcResult_PrimaryOutput(IDxcResult* This) {
    return This->lpVtbl->PrimaryOutput(This);
}
#endif
#endif

#endif


#endif  /* __IDxcResult_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IDxcCompiler3 interface
 */
#ifndef __IDxcCompiler3_INTERFACE_DEFINED__
#define __IDxcCompiler3_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDxcCompiler3, 0x228b4687, 0x5a6a, 0x4730, 0x90,0x0c, 0x97,0x02,0xb2,0x20,0x3f,0x54);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("228b4687-5a6a-4730-900c-9702b2203f54")
IDxcCompiler3 : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Compile(
        const DxcBuffer *source,
        const WCHAR **arguments,
        UINT32 arg_count,
        IDxcIncludeHandler *include_handler,
        REFIID riid,
        void **result) = 0;

    virtual HRESULT STDMETHODCALLTYPE Disassemble(
        const DxcBuffer *object,
        REFIID riid,
        void **result) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDxcCompiler3, 0x228b4687, 0x5a6a, 0x4730, 0x90,0x0c, 0x97,0x02,0xb2,0x20,0x3f,0x54)
#endif
#else
typedef struct IDxcCompiler3Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDxcCompiler3 *This,
        REFIID riid,
        void **object);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDxcCompiler3 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDxcCompiler3 *This);

    /*** IDxcCompiler3 methods ***/
    HRESULT (STDMETHODCALLTYPE *Compile)(
        IDxcCompiler3 *This,
        const DxcBuffer *source,
        const WCHAR **arguments,
        UINT32 arg_count,
        IDxcIncludeHandler *include_handler,
        REFIID riid,
        void **result);

    HRESULT (STDMETHODCALLTYPE *Disassemble)(
        IDxcCompiler3 *This,
        const DxcBuffer *object,
        REFIID riid,
        void **result);

    END_INTERFACE
} IDxcCompiler3Vtbl;

interface IDxcCompiler3 {
    CONST_VTBL IDxcCompiler3Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDxcCompiler3_QueryInterface(This,riid,object) (This)->lpVtbl->QueryInterface(This,riid,object)
#define IDxcCompiler3_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDxcCompiler3_Release(This) (This)->lpVtbl->Release(This)
/*** IDxcCompiler3 methods ***/
#define IDxcCompiler3_Compile(This,source,arguments,arg_count,include_handler,riid,result) (This)->lpVtbl->Compile(This,source,arguments,arg_count,include_handler,riid,result)
#define IDxcCompiler3_Disassemble(This,object,riid,result) (This)->lpVtbl->Disassemble(This,object,riid,result)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IDxcCompiler3_QueryInterface(IDxcCompiler3* This,REFIID riid,void **object) {
    return This->lpVtbl->QueryInterface(This,riid,object);
}
static __WIDL_INLINE ULONG IDxcCompiler3_AddRef(IDxcCompiler3* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IDxcCompiler3_Release(IDxcCompiler3* This) {
    return This->lpVtbl->Release(This);
}
/*** IDxcCompiler3 methods ***/
static __WIDL_INLINE HRESULT IDxcCompiler3_Compile(IDxcCompiler3* This,const DxcBuffer *source,const WCHAR **arguments,UINT32 arg_count,IDxcIncludeHandler *include_handler,REFIID riid,void **result) {
    return This->lpVtbl->Compile(This,source,arguments,arg_count,include_handler,riid,result);
}
static __WIDL_INLINE HRESULT IDxcCompiler3_Disassemble(IDxcCompiler3* This,const DxcBuffer *object,REFIID riid,void **result) {
    return This->lpVtbl->Disassemble(This,object,riid,result);
}
#endif
#endif

#endif


#endif  /* __IDxcCompiler3_INTERFACE_DEFINED__ */

typedef HRESULT (__stdcall *DxcCreateInstanceProc)(const IID *rclsid,REFIID riid,void **ppv);
#if defined(__x86_64__) && !defined(_WIN32)
# pragma pop_macro("__stdcall")
#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __dxcompiler_h__ */
